image: docker:latest

stages:
  - manual-trigger
  - basic-platform
  - other-platforms

.pull-request:
  only:
    - external_pull_requests

.builder:
  tags:
    - docker
  extends: .pull-request
  stage: other-platforms
  variables:
    GIT_SUBMODULE_STRATEGY: "normal"
    IMAGE_REGISTRY: "registry.gitlab.com/cig-pylith/pylith_installer"
    TEST_COVERAGE: "no"
  script:
    - docker build -t pylith-$BASE_IMAGE --build-arg BASE_IMAGE=$IMAGE_REGISTRY/$BASE_IMAGE --build-arg TEST_COVERAGE=$TEST_COVERAGE --build-arg PYTHON_COVERAGE=$PYTHON_COVERAGE --target build -f docker/pylith-testenv .
    - docker run -e CI_JOB_ID -e GITLAB_CI -e CI_BUILD_REF_NAME -e CI_BUILD_ID -e CI_BUILD_REPO -e CI_BUILD_REF -e CODECOV_TOKEN pylith-$BASE_IMAGE ci-config/run_tests.sh

.builder-first:
  extends: .builder
  stage: basic-platform

.doc:
  tags:
    - docker
  when: manual
  variables:
    IMAGE_REGISTRY: "registry.gitlab.com/cig-pylith/pylith_installer"
    BASE_IMAGE: "testenv-ubuntu-20.04"
  script:
    - docker build -t pylithdoc-$BASE_IMAGE --build-arg BASE_IMAGE=$IMAGE_REGISTRY/$BASE_IMAGE -f docker/pylith-docenv .

trigger-builds:
  stage: manual-trigger
  tags:
    - docker
  when: manual
  extends: .pull-request
  allow_failure: false
  script:
    - echo "Pipeline triggered manually"

debian-stable:
  extends: .builder-first
  variables:
    BASE_IMAGE: "testenv-debian-stable"
    PYTHON_COVERAGE: "python3-coverage"

debian-testing:
  extends: .builder
  variables:
    BASE_IMAGE: "testenv-debian-testing"
    PYTHON_COVERAGE: "python3-coverage"

ubuntu-18.04:
  extends: .builder
  variables:
    BASE_IMAGE: "testenv-ubuntu-18.04"
    PYTHON_COVERAGE: "python3-coverage"

ubuntu-20.04:
  extends: .builder
  variables:
    BASE_IMAGE: "testenv-ubuntu-20.04"
    PYTHON_COVERAGE: "python3-coverage"

ubuntu-21.04:
  extends: .builder
  variables:
    BASE_IMAGE: "testenv-ubuntu-21.04"
    PYTHON_COVERAGE: "python3-coverage"

fedora-33:
  extends: .builder
  variables:
    BASE_IMAGE: "testenv-fedora-33"
    PYTHON_COVERAGE: "coverage3"

fedora-34:
  extends: .builder
  variables:
    BASE_IMAGE: "testenv-fedora-34"
    PYTHON_COVERAGE: "coverage3"

centos-7:
  extends: .builder
  variables:
    BASE_IMAGE: "testenv-centos-7"

centos-8:
  extends: .builder
  variables:
    BASE_IMAGE: "testenv-centos-8"

build-docs:
  stage: manual-trigger
  extends:
    - .pull-request
    - .doc
