# Travis-CI configuration

dist: focal

services:
  - docker

language: cpp

# :TODO: @brad Add osx build (need homebrew packages)..
jobs:
  include:
    - name: debian-stable
      os: linux
      env: BASE_IMAGE=testenv-debian-stable TEST_COVERAGE=yes PYTHON_COVERAGE=python3-coverage
    - name: debian-testing
      os: linux
      env: BASE_IMAGE=testenv-debian-testing
    - name: ubuntu-18.04
      os: linux
      env: BASE_IMAGE=testenv-ubuntu-18.04
    - name: ubuntu-20.04
      os: linux
      env: BASE_IMAGE=testenv-ubuntu-20.04
    - name: ubuntu-20.10
      os: linux
      env: BASE_IMAGE=testenv-ubuntu-21.04
    - name: fedora-33
      os: linux
      env: BASE_IMAGE=testenv-fedora-33
    - name: fedora-34
      os: linux
      env: BASE_IMAGE=testenv-fedora-34
    - name: centos-7
      os: linux
      env: BASE_IMAGE=testenv-centos-7
    - name: centos-8
      os: linux
      env: BASE_IMAGE=testenv-centos-8

# Limit number of commits in cloning (but keep enough so that 'git describe' works)
git:
  depth: 100

install:
  - docker build -t pylith-testenv --build-arg BASE_IMAGE=registry.gitlab.com/cig-pylith/pylith_installer/$BASE_IMAGE --build-arg TEST_COVERAGE=$TEST_COVERAGE --build-arg PYTHON_COVERAGE=$PYTHON_COVERAGE --target build -f docker/pylith-testenv .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env pylith-testenv ci-config/run_tests.sh
